blank_issues_enabled: false
contact_links:
  - name: Jorvo.new related issues
    url: https://github.com/stackblitz/bolt.new/issues/new/choose
    about: Report issues related to Jorvo.new (not Jorvo.diy)
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other Jorvo.diy users.
